spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:./h2/easy-park
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    active: local

server:
  port: 8888